### ISSUE TITLE
如何在一个普通的html上使用.

### ISSUE THREAD

**Issue by Jim-Hepburn** [journey-ad/Snow-Typecho-Plugin#1]
如题，大佬，怎么在一个普通的html页面上展现出这样的特效啊，太好看了.

**Comment by journey-ad** [comment]
参考[这篇文章](https://imjad.cn/archives/code/sounds-winter-and-snowflakes-are-more-compatible/)

**Comment by Jim-487438545** [comment]
好的👌谢谢!


 
---原始邮件---
发件人: "Jad"<notifications@github.com&gt;
发送时间: 2020年4月12日 14:31:32
收件人: "journey-ad/Snow-Typecho-Plugin"<Snow-Typecho-Plugin@noreply.github.com&gt;;
抄送: "Jim"<487438545@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [journey-ad/Snow-Typecho-Plugin] 如何在一个普通的html上使用. (#1)




 
参考这篇文章
